name: Git Repository Backup to S3
run-name: Backup ${{ github.event.repository.name }} (${{ github.sha || github.event.after || github.event.head_commit.id || 'no-sha' }}) to S3

on:
  push:
     branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    steps:
      - uses: actions/checkout@v6
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::224475991521:role/webops-github-backup
          role-duration-seconds: 3600
          aws-region: us-east-1
      - name: Create Bundle
        run: |
         git bundle create ${{github.event.repository.name}}.bundle --all
      - name: Backup to S3
        run: |
          aws s3 cp ${{github.event.repository.name}}.bundle s3://agilix-e1-mt/github/ --sse --storage-class STANDARD_IA
