name: S3 Backup
on:
  push:
     branches: '**'

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - name: S3 Backup
       uses: peter-evans/s3-backup@v1.1.1
       env:
        ACCESS_KEY_ID: ${{ secrets.S3BACKUPKEY2023 }}
        SECRET_ACCESS_KEY: ${{ secrets.S3BACKUPKEYVALUE2023 }}
        MIRROR_TARGET: agilix-e1-mt/github/${{GITHUB.REPOSITORY }}
       with:
        args: --overwrite --remove
